language: minimal
env:
  global:
    - HELM_VERSION="v2.12.3"
services:
  - docker
install:
  - bash install.sh
script:
  - travis_wait docker build -t scos-kube-bench:build .
deploy:
- provider: script
  skip_cleanup: true
  script: bash deploy.sh master
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: bash deploy.sh release
  on:
    tags: true
branches:
  only:
  - master
  - /\d{1,3}\.\d{1,3}\.\d{1,3}/